<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Panda\JsFun\ViewModel\Message $messageViewModel */
$messageViewModel = $block->getData('message_view_model');
?>

<div id="vue-test">
    <h1>{{ message }}</h1>
</div>

<script type="text/x-magento-init">
    {
        "#vue-test": {
            "Panda_JsFun/js/vue-test": {
                "message": "<?= $messageViewModel->getMessage() ?>"
            }
        }
    }
</script>
